### ISSUE TITLE
Log Terminal

### ISSUE THREAD

**Issue by folknor** [CoderDE/FicsIt-Networks#11]
Hi,

Thanks, this mod rocks! Here's my first feature request: Logging.

I'm not sure if you're aware of [serpent](https://github.com/pkulchenko/serpent), but it's one of the most used lua libraries in existence. It would be excellent if it could be provided in the global namespace for us to use. Factorio does this, for example, and just simply exposes it as `serpent`, if I remember correctly.

For logging itself, there's two options, and frankly I'd prefer it if both were available:
1. Logging through SML to stdout/err. I'm not sure where this log ends up on Windows, but when I run Satisfactory through wine on Linux, I get the log messages in dmesg along with the rest of the system log, so I can just run `journalctl -f` to monitor it
1. Logging to an ingame terminal / display

Logging to stdout would be the most useful, but logging to an ingame terminal would be "cool" :-)

Thank you again!

**Comment by Panakotta00** [comment]
I quite don't understand it fully... you can log already stuff ingame by the usage of the "print" command...
later on we will create our own "Lua OS" which then can have logging library integrated allowing you to log to the serial out of the ingame PC, a file in a ingame VFS or to the ingame PC.

Logging to the real std out is... kinda expensive if you do it a lot (like in a while true loop)

**Comment by Panakotta00** [comment]
If you mean a serialization library, yes that probably will get added (hopefully human-readable and minimal).

And I'm glad you like it, for now ^^

**Comment by Panakotta00** [comment]
So I did some research,
and such a serialization library will probably get implemented in Lua itself, later when we create a "Lua OS".
That Lua OS will then probably also implement some other logging functionality since it will very likely simply control everything that is displayed to a ingame monitor. That will render any other logging capability exposed from native code useless since it gets managed by the OS.

Reopen the Issue if you want to further discuss this topic ^^
