### ISSUE TITLE
Bundle eris source code for easier from source builds

### ISSUE THREAD

**Issue by UplinkCoder** [CoderDE/FicsIt-Networks#146]
I've just tried to build FicsIt-Networks from source and I've discovered that the bundled eris.lib doesn't seem to link when using VS2017.
Would it be possible to include eris in the source-tree and add a build step such that issues with mismatching binary versions can be ruled out?

Thanks,
Stefan

for completeness the error message I get is:
```
1>  eris.lib(lstate.obj) : MSIL .netmodule or module compiled with /GL found; restarting link with /LTCG; add /LTCG to the link command line to improve linker performance
1>EXEC : fatal error C1900: Il mismatch between 'P1' version '20190715' and 'P2' version '20180423'
1>LINK : fatal error LNK1257: code generation failed
```

**Comment by Panakotta00** [comment]
VS2017 is generally not really supported...
We use (also in CI) MSVC 14.26.28806 (as far as i can tell) and windows 10.0.18362.0 SDK
I'm not sure but you might even have otherwise issues with the VFS and C++17...
You should be able to use VS 2017 itself but you have to install the MSVC toolchain and win SDK given

**Comment by UplinkCoder** [comment]
@Panakotta00 Interesting the SML wiki says to use VS2017 or VS2019.  (https://docs.ficsit.app/satisfactory-modding/latest/Development/BeginnersGuide/dependencies.html)
I take it that is out of date info?

**Comment by Panakotta00** [comment]
I guess SML itself etc works with VS2017
FIN does not and requires VS2019
